version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - echo Building the application...
      # Add any build commands specific to your application
  post_build:
    commands:
      - echo Build completed on `date`
